export const productConstants={
    PRODUCT_LIST_REQUEST:"PRODUCT_LIST_REQUEST",
    PRODUCT_LIST_SUCCESS:"PRODUCT_LIST_SUCCESS",
    PRODUCT_LIST_FAILURE:"PRODUCT_LIST_FAILURE",
}

export const productDetailsConstants={
    PRODUCT_DETAILS_REQUEST:"PRODUCT_DETAILS_REQUEST",
    PRODUCT_DETAILS_SUCCESS:"PRODUCT_DETAILS_SUCCESS",
    PRODUCT_DETAILS_FAILURE:"PRODUCT_DETAILS_FAILURE",
}

export const cartConstants={
    CART_ADD_ITEM:"CART_ADD_ITEM",
    CART_REMOVE_ITEM:"CART_REMOVE_ITEM",
    CART_SAVE_SHIPPING_ADDRESS:"CART_SAVE_SHIPPING_ADDRESS",
    CART_SAVE_PAYMENT_METHOD:"CART_SAVE_PAYMENT_METHOD",
    CART_EMPTY: "CART_EMPTY"
}
export const userConstants={
    USER_SIGNIN_REQUEST : "USER_SIGNIN_REQUEST",
    USER_SIGNIN_SUCCESS : "USER_SIGNIN_SUCCESS",
    USER_SIGNIN_FAILURE : "USER_SIGNIN_FAILURE",
    USER_SIGNOUT : "USER_SIGNOUT",
    USER_DETAILS_REQUEST : "USER_DETAILS_REQUEST",
    USER_DETAILS_SUCCESS : "USER_DETAILS_SUCCESS",
    USER_DETAILS_FAILURE : "USER_DETAILS_FAILURE",

    USER_REGISTER_REQUEST : "USER_REGISTER_REQUEST",
    USER_REGISTER_SUCCESS : "USER_REGISTER_SUCCESS",
    USER_REGISTER_FAILURE : "USER_REGISTER_FAILURE",

    USER_UPDATE_PROFILE_REQUEST : "USER_UPDATE_PROFILE_REQUEST",
    USER_UPDATE_PROFILE_SUCCESS : "USER_UPDATE_PROFILE_SUCCESS",
    USER_UPDATE_PROFILE_FAILURE : "USER_UPDATE_PROFILE_FAILURE",
    USER_UPDATE_PROFILE_RESET : "USER_UPDATE_PROFILE_RESET",
}

export const orderConstants = {
    ORDER_CREATE_REQUEST:"ORDER_CREATE_REQUEST",
    ORDER_CREATE_SUCCESS:"ORDER_CREATE_SUCCESS",
    ORDER_CREATE_FAILURE:"ORDER_CREATE_FAILURE",
    ORDER_CREATE_RESET:"ORDER_CREATE_RESET",
    ORDER_DETAILS_REQUEST:"ORDER_DETAILS_REQUEST",
    ORDER_DETAILS_SUCCESS:"ORDER_DETAILS_SUCCESS",
    ORDER_DETAILS_FAILURE:"ORDER_DETAILS_FAILURE",
}